#
###################################
# Site wide configuration
####################################
#
title: MetaData
email: dataitgirls.metadata@gmail.comë¥¼
description: MetaDataëŠ” ì• ìì¼í•œ ì¡°ì§ìœ¼ë¡œ íŒŒíŠ¸ë„ˆì™€ í•¨ê»˜ ì„±ì¥í•˜ê¸°ë¥¼ ë°”ëë‹ˆë‹¤
url: https://meta-data.github.io/
keywords: ["blog", "jekyll", "Data", "analysis", "KPI", "GA", "ë°ì‡ê±¸ì¦ˆ", "ë©”íƒ€ë°ì´í„°", "ë°ì´í„°ë¶„ì„"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: MetaData
  avatar: logo.png
  bio: "ë°ì‡ê±¸ì¦ˆ 2ê¸°"
  desc: "í˜„ì¥ì—ì„œ ì¨ë¨¹ì§€ ëª»í•˜ëŠ” ì§€ì‹ì€ ğŸ’©ëœë‹¤"
  email: "dataitgirls.metadata@gmail.com"
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: #"UA-125813740-1"
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: "https://github.com/meta-data"
  linkedin: #username
  instagram: #username
  pinterest: #username
  reddit: #username
  telegram: #username